/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as tippingAndAirdropSol from "./TippingAndAirdrop.sol";
export type { tippingAndAirdropSol };
export type { EchoeCampaignsV1 } from "./EchoeCampaignsV1";
export type { Lock } from "./Lock";
export type { Payfluence } from "./Payfluence";
export type { PlatformRegistry } from "./PlatformRegistry";
export type { TestERC20 } from "./TestERC20";
export type { TokenReceiver } from "./TokenReceiver";
