"use client";

import "@repo/ui/globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";

import * as dotenv from 'dotenv';
dotenv.config();

import { QueryClient, QueryClientProvider } from '@tanstack/react-query'
import { WagmiProvider } from 'wagmi'
import { WalletContextProvider } from "@/app/context/WalletContext";

import {
  DynamicContextProvider,
} from "@dynamic-labs/sdk-react-core";
import { EthereumWalletConnectors } from "@dynamic-labs/ethereum";

import { wagmiConfig } from '@/config/web3';

const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Docs",
//   description: "Generated by create turbo",
// };

const dynamicContextLocale = {
  en: {
    dyn_login: {
      title: {
        all: "",
      },
    },
  },
};

const queryClient = new QueryClient()

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}): JSX.Element {
  return (
    <html lang="en">
      <body className={inter.className}>

        <WagmiProvider config={wagmiConfig}>
          <QueryClientProvider client={queryClient}> 
            <WalletContextProvider>
          
        <DynamicContextProvider
          locale={dynamicContextLocale}
          settings={{
            // Find your environment id at https://app.dynamic.xyz/dashboard/developer
            environmentId: process.env.NEXT_PUBLIC_DYNAMIC_ENVIRONMENT_ID || "sandbox",
            walletConnectors: [EthereumWalletConnectors],
          }}
        >
          {children}
        </DynamicContextProvider>

            </WalletContextProvider>
          </QueryClientProvider> 
        </WagmiProvider>
      </body>
    </html>
  );
}
