// Generated by Wrangler on Thu Jun 27 2024 00:44:21 GMT-0400 (Eastern Daylight Saving Time)
// by running `wrangler types`

interface Env {
	ALLOWANCE_KV: KVNamespace;
	NEYNAR_API_KEY: string;
	ALCHEMY_BASE_SEPOLIA: string;
	ALCHEMY_BASE_MAINNET: string;
}
